spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/adventure_book
    username: adventure
    password: local_dev_password

springdoc:
  api-docs:
    path: /api-docs

management:
  endpoint:
    health:
      show-details: always
