spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/adventure_book
    username: adventure
    password: local_dev_password

management:
  endpoint:
    health:
      show-details: always
