spring:
  application:
    name: adventure-book-api
  mvc:
    problemdetails:
      enabled: true

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

springdoc:
  api-docs:
    path: /api-docs

management:
  health:
    db:
      enabled: true
